"use client";

import {
  Activity,
  LockKeyhole,
  RadioTower,
  Send,
  ShieldCheck,
  UserCheck,
} from "lucide-react";
import { useQuery } from "@tanstack/react-query";

import { ActionButton } from "@/components/action-button";
import { useAssetContext } from "@/components/asset-provider";
import { DataTable } from "@/components/data-table";
import { ErrorState } from "@/components/error-state";
import { KpiCard } from "@/components/kpi-card";
import { PageHeading } from "@/components/page-heading";
import { SectionCard } from "@/components/section-card";
import { StatusPill } from "@/components/status-pill";
import { apiGet } from "@/lib/api";
import { formatCurrency, formatDateTime, formatNumber } from "@/lib/format";
import type {
  ExecutionProposalHistoryResponse,
  ExecutionProposalResponse,
  LatestSignalResponse,
} from "@/types/api";

export default function ExecutionPage() {
  const { selectedAsset, selectedAssetId } = useAssetContext();

  const latestProposal = useQuery({
    queryFn: () =>
      apiGet<ExecutionProposalResponse>(
        `/assets/${selectedAssetId}/execution/proposal/latest`,
      ),
    queryKey: ["execution-proposal-latest", selectedAssetId],
  });

  const proposalHistory = useQuery({
    queryFn: () =>
      apiGet<ExecutionProposalHistoryResponse>(
        `/assets/${selectedAssetId}/execution/proposals?limit=10`,
      ),
    queryKey: ["execution-proposal-history", selectedAssetId],
  });

  const signal = useQuery({
    queryFn: () =>
      apiGet<LatestSignalResponse>(`/assets/${selectedAssetId}/signal/latest`),
    queryKey: ["execution-signal-latest", selectedAssetId],
  });

  const proposal = latestProposal.data?.proposal;
  const signalSummary = signal.data?.data?.summary ?? {};
  const orders = proposal?.orders ?? [];
  const riskChecks = proposal?.risk_checks ?? [];
  const auditRows = proposal?.audit ?? [];
  const automationBlockers = proposal?.automation_blockers ?? [];
  const hardBlockers = proposal?.blockers ?? [];
  const summary = proposal?.summary ?? {};
  const expectedPnl = Number(
    summary.expected_pnl_eur ?? signalSummary.total_pnl_eur ?? 0,
  );
  const profitPerMwDay =
    summary.profit_per_mw_day ?? signalSummary.profit_per_mw_day;

  const refetchExecution = () =>
    Promise.all([latestProposal.refetch(), proposalHistory.refetch()]);

  return (
    <>
      <PageHeading
        description="Build backend-controlled pre-trade proposal packets from the latest dispatch signal, workflow audit record, risk checks, approval state, and future market adapter requirements."
        eyebrow="Trading control plane"
        title="Execution"
      />

      <div className="mb-6 flex flex-wrap gap-3">
        <ActionButton
          endpoint={`/assets/${selectedAssetId}/execution/proposal/build`}
          label="Build pre-trade proposal"
          refetch={refetchExecution}
          variant="primary"
        />
      </div>

      {latestProposal.data?.status === "not_found" ? (
        <div className="mb-6">
          <ErrorState message="No backend execution proposal exists yet. Build a pre-trade proposal after generating a signal or audited workflow." />
        </div>
      ) : null}

      <div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <KpiCard
          accent={proposal?.status === "draft" ? "emerald" : "amber"}
          label="Proposal status"
          value={proposal?.status ?? "-"}
          helper={
            proposal?.approval_status ??
            (signal.data?.status === "ok"
              ? "Signal ready for proposal"
              : "No approval state")
          }
        />
        <KpiCard
          accent={orders.length ? "blue" : "slate"}
          label="Draft orders"
          value={orders.length}
          helper="Generated by backend pre-trade engine"
        />
        <KpiCard
          accent={expectedPnl >= 0 ? "emerald" : "red"}
          label="Expected PnL"
          value={formatCurrency(expectedPnl)}
          helper={`${formatNumber(profitPerMwDay, 2)} EUR/MW-day`}
        />
        <KpiCard
          accent="blue"
          label="Asset"
          value={selectedAsset?.asset_name ?? selectedAsset?.site_name ?? selectedAssetId}
          helper={proposal?.market ?? selectedAsset?.market ?? "DE-LU day-ahead"}
        />
      </div>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.35fr)_minmax(380px,0.85fr)]">
        <div className="space-y-5">
          <SectionCard
            action={<StatusPill tone="amber">Market submission disabled</StatusPill>}
            title="Backend proposed market orders"
          >
            <DataTable
              columns={[
                "order_id",
                "delivery_time",
                "market",
                "side",
                "volume_mwh",
                "price_limit_eur_mwh",
                "status",
              ]}
              rows={orders}
            />
          </SectionCard>

          <SectionCard title="Approval workflow">
            <div className="grid gap-3 md:grid-cols-4">
              <WorkflowStep
                icon={<Activity className="h-4 w-4" />}
                label="Signal linked"
                status={proposal?.signal_id ? "complete" : "pending"}
              />
              <WorkflowStep
                icon={<ShieldCheck className="h-4 w-4" />}
                label="Risk checks"
                status={hardBlockers.length ? "blocked" : orders.length ? "complete" : "pending"}
              />
              <WorkflowStep
                icon={<UserCheck className="h-4 w-4" />}
                label="Human approval"
                status={proposal?.approval_status === "requires_approval" ? "required" : "pending"}
              />
              <WorkflowStep
                icon={<Send className="h-4 w-4" />}
                label="Market submission"
                status="disabled"
              />
            </div>
          </SectionCard>

          <SectionCard title="Proposal history">
            <DataTable
              columns={[
                "execution_proposal_id",
                "generated_at",
                "status",
                "approval_status",
                "signal_id",
                "workflow_run_id",
                "order_count",
                "expected_pnl_eur",
              ]}
              rows={formatProposalHistory(proposalHistory.data?.proposals ?? [])}
            />
          </SectionCard>
        </div>

        <div className="space-y-5">
          <SectionCard title="Execution readiness">
            <div className="space-y-3">
              <ReadinessRow
                icon={<RadioTower className="h-4 w-4" />}
                label="Market API connection"
                tone="amber"
                value="Not connected"
              />
              <ReadinessRow
                icon={<Activity className="h-4 w-4" />}
                label="Asset telemetry"
                tone="amber"
                value="Not connected"
              />
              <ReadinessRow
                icon={<UserCheck className="h-4 w-4" />}
                label="Approval mode"
                tone="blue"
                value={proposal?.approval_status ?? "Not built"}
              />
              <ReadinessRow
                icon={<LockKeyhole className="h-4 w-4" />}
                label="Audit logging"
                tone={proposal?.execution_proposal_id ? "emerald" : "slate"}
                value={proposal?.execution_proposal_id ? "Proposal persisted" : "Pending"}
              />
            </div>
          </SectionCard>

          <SectionCard title="Position limits">
            <DataTable
              columns={["limit", "value", "status"]}
              rows={[
                {
                  limit: "Total buy energy",
                  status: "draft",
                  value: `${formatNumber(
                    summary.total_buy_mwh ?? signalSummary.charged_mwh,
                    2,
                  )} MWh`,
                },
                {
                  limit: "Total sell energy",
                  status: "draft",
                  value: `${formatNumber(
                    summary.total_sell_mwh ?? signalSummary.discharged_mwh,
                    2,
                  )} MWh`,
                },
                {
                  limit: "Max loss per day",
                  status: expectedPnl > -Number(summary.max_daily_loss_eur ?? 0) ? "within limit" : "breach",
                  value: formatCurrency(summary.max_daily_loss_eur),
                },
                {
                  limit: "Linked workflow",
                  status: proposal?.workflow_run_id ? "linked" : "not linked",
                  value: proposal?.workflow_run_id ?? "-",
                },
              ]}
            />
          </SectionCard>

          <SectionCard
            action={<StatusPill tone={hardBlockers.length ? "red" : "blue"}>{hardBlockers.length}</StatusPill>}
            title="Hard blockers"
          >
            <DataTable
              columns={["blocker"]}
              rows={hardBlockers.map((blocker) => ({ blocker }))}
            />
          </SectionCard>

          <SectionCard
            action={<StatusPill tone="amber">{automationBlockers.length}</StatusPill>}
            title="Automation blockers"
          >
            <DataTable
              columns={["blocker"]}
              rows={automationBlockers.map((blocker) => ({ blocker }))}
            />
          </SectionCard>
        </div>
      </div>

      <div className="mt-5 grid gap-5 xl:grid-cols-2">
        <SectionCard title="Backend risk checks">
          <DataTable
            columns={["check", "status", "message", "context"]}
            rows={riskChecks}
          />
        </SectionCard>

        <SectionCard
          action={<StatusPill tone="blue">Pre-trade audit</StatusPill>}
          title="Execution audit trail"
        >
          <DataTable
            columns={["event", "actor", "status", "note"]}
            rows={auditRows}
          />
        </SectionCard>
      </div>
    </>
  );
}

function formatProposalHistory(rows: NonNullable<ExecutionProposalHistoryResponse["proposals"]>) {
  return rows.map((row) => ({
    ...row,
    generated_at: formatDateTime(row.generated_at),
  }));
}

function WorkflowStep({
  icon,
  label,
  status,
}: {
  icon: React.ReactNode;
  label: string;
  status: "blocked" | "complete" | "disabled" | "pending" | "required";
}) {
  const toneByStatus = {
    blocked: "red",
    complete: "emerald",
    disabled: "amber",
    pending: "slate",
    required: "blue",
  } as const;

  return (
    <div className="rounded-lg border border-slate-800 bg-slate-900/45 p-4">
      <div className="flex items-center gap-2 text-sm font-semibold text-slate-200">
        <span className="text-sky-300">{icon}</span>
        {label}
      </div>
      <div className="mt-4">
        <StatusPill tone={toneByStatus[status]}>{status}</StatusPill>
      </div>
    </div>
  );
}

function ReadinessRow({
  icon,
  label,
  tone,
  value,
}: {
  icon: React.ReactNode;
  label: string;
  tone: "amber" | "blue" | "emerald" | "red" | "slate";
  value: React.ReactNode;
}) {
  return (
    <div className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-900/45 px-4 py-3">
      <div className="flex min-w-0 items-center gap-3">
        <span className="text-slate-400">{icon}</span>
        <span className="text-sm text-slate-300">{label}</span>
      </div>
      <StatusPill tone={tone}>{value}</StatusPill>
    </div>
  );
}
