CLIENT_PRESETS = {
    "small_battery": {
        "client_name": "Demo Small Battery Client",
        "site_name": "Small Commercial Battery",
        "country": "Germany",
        "market": "Day-ahead spot",
        "market_profile_id": "de_lu_day_ahead",
        "battery_config": {
            "capacity_mwh": 5.0,
            "initial_soc_mwh": 2.5,
            "min_soc_mwh": 0.5,
            "max_charge_power_mw": 2.5,
            "max_discharge_power_mw": 2.5,
            "charge_efficiency": 0.95,
            "discharge_efficiency": 0.95,
        },
        "strategy_config": {
            "low_price_threshold": 20.0,
            "high_price_threshold": 80.0,
            "timestep_hours": 0.25,
        },
        "commercial_config": {
            "trading_fee_eur_per_mwh": 0.20,
            "market_access_fee_eur_per_mwh": 0.30,
            "grid_fee_import_eur_per_mwh": 0.0,
            "grid_fee_export_eur_per_mwh": 0.0,
            "tax_or_levy_eur_per_mwh": 0.0,
            "degradation_cost_eur_per_mwh_throughput": 3.0,
        },
    },
    "grid_scale_battery": {
        "client_name": "Demo Battery Client",
        "site_name": "Demo Grid Scale Battery",
        "country": "Germany",
        "market": "Day-ahead spot",
        "market_profile_id": "de_lu_day_ahead",
        "battery_config": {
            "capacity_mwh": 20.0,
            "initial_soc_mwh": 10.0,
            "min_soc_mwh": 2.0,
            "max_charge_power_mw": 10.0,
            "max_discharge_power_mw": 10.0,
            "charge_efficiency": 0.95,
            "discharge_efficiency": 0.95,
        },
        "strategy_config": {
            "low_price_threshold": 20.0,
            "high_price_threshold": 80.0,
            "timestep_hours": 0.25,
        },
        "commercial_config": {
            "trading_fee_eur_per_mwh": 0.20,
            "market_access_fee_eur_per_mwh": 0.30,
            "grid_fee_import_eur_per_mwh": 0.0,
            "grid_fee_export_eur_per_mwh": 0.0,
            "tax_or_levy_eur_per_mwh": 0.0,
            "degradation_cost_eur_per_mwh_throughput": 3.0,
        },
    },
    "large_battery": {
        "client_name": "Demo Large Battery Client",
        "site_name": "Large Grid Battery",
        "country": "Germany",
        "market": "Day-ahead spot",
        "market_profile_id": "de_lu_day_ahead",
        "battery_config": {
            "capacity_mwh": 100.0,
            "initial_soc_mwh": 50.0,
            "min_soc_mwh": 10.0,
            "max_charge_power_mw": 50.0,
            "max_discharge_power_mw": 50.0,
            "charge_efficiency": 0.95,
            "discharge_efficiency": 0.95,
        },
        "strategy_config": {
            "low_price_threshold": 20.0,
            "high_price_threshold": 80.0,
            "timestep_hours": 0.25,
        },
        "commercial_config": {
            "trading_fee_eur_per_mwh": 0.20,
            "market_access_fee_eur_per_mwh": 0.30,
            "grid_fee_import_eur_per_mwh": 0.0,
            "grid_fee_export_eur_per_mwh": 0.0,
            "tax_or_levy_eur_per_mwh": 0.0,
            "degradation_cost_eur_per_mwh_throughput": 3.0,
        },
    },
}
