import type { NavigationGroupId } from "@/lib/navigation";

export const PERSONA_IDS = [
  "all",
  "asset_owner",
  "investor_lender",
  "project_developer",
  "executive",
  "client_success",
  "trading_desk",
  "automation_operator",
  "risk_compliance",
  "market_operations",
  "forecast_quant",
  "revenue_analyst",
] as const;

export type PersonaId = (typeof PERSONA_IDS)[number];

export const DEFAULT_PERSONA_ID: PersonaId = "all";

export const VISIBLE_PERSONA_IDS = [
  "all",
  "asset_owner",
  "investor_lender",
  "project_developer",
  "executive",
  "client_success",
  "trading_desk",
  "automation_operator",
  "risk_compliance",
  "market_operations",
  "forecast_quant",
  "revenue_analyst",
] as const satisfies readonly PersonaId[];

export type PersonaLayer = "client" | "internal" | "platform";

export const PERSONA_GROUPS = [
  {
    ids: ["all"],
    label: "Platform",
  },
  {
    ids: [
      "asset_owner",
      "investor_lender",
      "project_developer",
      "executive",
      "client_success",
    ],
    label: "Client Evidence Portal",
  },
  {
    ids: [
      "trading_desk",
      "automation_operator",
      "risk_compliance",
      "market_operations",
      "forecast_quant",
      "revenue_analyst",
    ],
    label: "Internal Trading OS",
  },
] as const satisfies readonly {
  ids: readonly PersonaId[];
  label: string;
}[];

export type PersonaProfile = {
  allowedAutomationActions: string[];
  allowedNavigationHrefs: string[];
  defaultNavigationHref: string;
  defaultNavigationLabel: string;
  id: PersonaId;
  label: string;
  layer: PersonaLayer;
  header: string;
  focus: string;
  defaultControlRoomTab: "trading" | "readiness" | "commercial" | "execution" | "actions";
  primaryNavigationGroups: NavigationGroupId[];
  priorityActions: string[];
  priorityKpis: string[];
};

const allNavigationHrefs = [
  "/",
  "/assets",
  "/intelligence",
  "/revenue",
  "/reports",
  "/forecasts",
  "/market-prices",
  "/market-signals",
  "/market-rules",
  "/dispatch",
  "/scenarios",
  "/hedging",
  "/execution/automation-policies",
  "/execution/orchestrator",
  "/execution",
  "/execution/market-allocation",
  "/execution/proposals",
  "/execution/simulation",
  "/execution/market-connectors",
  "/execution/risk-approval",
  "/regulation",
  "/execution/settlement",
  "/execution/audit",
  "/settings",
];

export const personaProfiles: Record<PersonaId, PersonaProfile> = {
  all: {
    id: "all",
    label: "Full platform",
    layer: "platform",
    header: "Enterprise platform",
    focus: "Full client evidence portal and internal trading operating system.",
    defaultNavigationHref: "/",
    defaultNavigationLabel: "Control Room",
    defaultControlRoomTab: "trading",
    primaryNavigationGroups: [
      "portfolio",
      "market_intelligence",
      "optimization",
      "automated_trading",
      "risk_compliance",
    ],
    allowedNavigationHrefs: allNavigationHrefs,
    priorityActions: [
      "Monitor portfolio control room.",
      "Review market signal and automation readiness.",
      "Keep audit evidence current.",
    ],
    priorityKpis: ["automation_mode", "expected_pnl", "readiness_score"],
    allowedAutomationActions: ["build_proposal", "run_paper_trade", "request_human_gate"],
  },
  asset_owner: {
    id: "asset_owner",
    label: "Asset owner",
    layer: "client",
    header: "Client evidence portal",
    focus: "Revenue, readiness, blockers, settlement proof, and client reporting.",
    defaultNavigationHref: "/revenue",
    defaultNavigationLabel: "Revenue Assurance",
    defaultControlRoomTab: "commercial",
    primaryNavigationGroups: ["portfolio", "optimization", "risk_compliance"],
    allowedNavigationHrefs: [
      "/",
      "/assets",
      "/revenue",
      "/reports",
      "/execution/settlement",
      "/execution/audit",
      "/regulation",
      "/hedging",
    ],
    priorityActions: [
      "Review expected PnL and revenue stack.",
      "Check evidence readiness before client delivery.",
      "Confirm settlement and audit blockers before approving automation claims.",
    ],
    priorityKpis: ["modelled_revenue", "downside_risk", "production_readiness"],
    allowedAutomationActions: ["view_status", "approve_gate"],
  },
  investor_lender: {
    id: "investor_lender",
    label: "Investor / lender",
    layer: "client",
    header: "Bankability view",
    focus: "Revenue certainty, downside protection, auditability, and regulatory evidence.",
    defaultNavigationHref: "/hedging",
    defaultNavigationLabel: "Hedging",
    defaultControlRoomTab: "commercial",
    primaryNavigationGroups: ["portfolio", "optimization", "risk_compliance"],
    allowedNavigationHrefs: [
      "/",
      "/assets",
      "/revenue",
      "/hedging",
      "/reports",
      "/execution/audit",
      "/execution/settlement",
      "/regulation",
      "/scenarios",
    ],
    priorityActions: [
      "Review bankable revenue and downside protection.",
      "Check audit evidence and settlement variance.",
      "Use client reports before investment or lending review.",
    ],
    priorityKpis: ["bankability", "settlement_variance", "evidence_score"],
    allowedAutomationActions: ["view_status"],
  },
  project_developer: {
    id: "project_developer",
    label: "Project developer",
    layer: "client",
    header: "Development readiness",
    focus: "Pre-COD revenue, technical readiness, market eligibility, and regulatory assumptions.",
    defaultNavigationHref: "/scenarios",
    defaultNavigationLabel: "Scenario Lab",
    defaultControlRoomTab: "readiness",
    primaryNavigationGroups: ["portfolio", "market_intelligence", "optimization", "risk_compliance"],
    allowedNavigationHrefs: [
      "/",
      "/assets",
      "/scenarios",
      "/hedging",
      "/market-rules",
      "/market-prices",
      "/regulation",
      "/revenue",
      "/reports",
      "/forecasts",
    ],
    priorityActions: [
      "Validate market eligibility before investment commitment.",
      "Compare scenario economics and grid assumptions.",
      "Package readiness evidence for stakeholders.",
    ],
    priorityKpis: ["scenario_value", "market_eligibility", "readiness_score"],
    allowedAutomationActions: ["view_status", "run_scenarios"],
  },
  executive: {
    id: "executive",
    label: "Executive",
    layer: "client",
    header: "Executive view",
    focus: "Portfolio performance, strategic readiness, commercial value, and major blockers.",
    defaultNavigationHref: "/",
    defaultNavigationLabel: "Control Room",
    defaultControlRoomTab: "trading",
    primaryNavigationGroups: ["portfolio", "risk_compliance", "optimization"],
    allowedNavigationHrefs: [
      "/",
      "/intelligence",
      "/revenue",
      "/reports",
      "/execution/audit",
      "/execution/settlement",
      "/regulation",
      "/scenarios",
    ],
    priorityActions: [
      "Review portfolio signal, expected PnL, and automation blockers.",
      "Check automation maturity and revenue stack direction.",
      "Use reports for board or customer-facing evidence.",
    ],
    priorityKpis: ["portfolio_pnl", "automation_maturity", "top_blocker"],
    allowedAutomationActions: ["view_status"],
  },
  client_success: {
    id: "client_success",
    label: "Client success",
    layer: "client",
    header: "Client delivery view",
    focus: "Explain performance, blockers, settlement, audit evidence, and next actions to clients.",
    defaultNavigationHref: "/reports",
    defaultNavigationLabel: "Reports",
    defaultControlRoomTab: "actions",
    primaryNavigationGroups: ["portfolio", "risk_compliance", "optimization"],
    allowedNavigationHrefs: [
      "/",
      "/reports",
      "/revenue",
      "/intelligence",
      "/execution/settlement",
      "/execution/audit",
      "/regulation",
      "/assets",
      "/hedging",
    ],
    priorityActions: [
      "Generate the selected-asset client report.",
      "Explain open evidence gaps and next actions.",
      "Use settlement and audit evidence to support performance conversations.",
    ],
    priorityKpis: ["client_readiness", "evidence_score", "open_gaps"],
    allowedAutomationActions: ["view_status"],
  },
  trading_desk: {
    id: "trading_desk",
    label: "Trading desk",
    layer: "internal",
    header: "Internal trading OS",
    focus: "Signals, market routes, bid packages, paper trading, and supervised/live execution.",
    defaultNavigationHref: "/execution",
    defaultNavigationLabel: "Mission Control",
    defaultControlRoomTab: "execution",
    primaryNavigationGroups: ["automated_trading", "market_intelligence", "optimization", "risk_compliance"],
    allowedNavigationHrefs: [
      "/execution",
      "/execution/orchestrator",
      "/execution/market-allocation",
      "/execution/proposals",
      "/execution/simulation",
      "/dispatch",
      "/market-signals",
      "/market-prices",
      "/market-rules",
      "/forecasts",
      "/execution/automation-policies",
      "/execution/risk-approval",
    ],
    priorityActions: [
      "Check automation mode and next action.",
      "Select market route and build bid package.",
      "Run paper validation before supervised or live submission.",
    ],
    priorityKpis: ["automation_mode", "primary_market", "next_auto_action"],
    allowedAutomationActions: ["build_proposal", "run_paper_trade", "request_human_gate", "simulate_submission"],
  },
  automation_operator: {
    id: "automation_operator",
    label: "Automation operator",
    layer: "internal",
    header: "Internal automation OS",
    focus: "Automation mode, gates, limits, remediation, market connectivity, and live-readiness escalation.",
    defaultNavigationHref: "/execution/automation-policies",
    defaultNavigationLabel: "Automation Control",
    defaultControlRoomTab: "execution",
    primaryNavigationGroups: ["automated_trading", "risk_compliance", "market_intelligence"],
    allowedNavigationHrefs: [
      "/assets",
      "/execution/automation-policies",
      "/execution/orchestrator",
      "/execution",
      "/execution/risk-approval",
      "/execution/proposals",
      "/execution/market-connectors",
      "/market-signals",
      "/execution/simulation",
      "/execution/settlement",
      "/settings",
    ],
    priorityActions: [
      "Keep the automation control plane unblocked.",
      "Escalate from paper to supervised only with evidence.",
      "Track connector and telemetry gates before limited live mode.",
    ],
    priorityKpis: ["live_trading_allowed", "human_gate", "blocker_count"],
    allowedAutomationActions: ["build_proposal", "run_paper_trade", "simulate_submission", "enable_supervised_auto"],
  },
  risk_compliance: {
    id: "risk_compliance",
    label: "Risk & compliance",
    layer: "internal",
    header: "Governance OS",
    focus: "Automation gates, approval policy, settlement, audit, regulation, reports, and operating limits.",
    defaultNavigationHref: "/execution/risk-approval",
    defaultNavigationLabel: "Automation Gates",
    defaultControlRoomTab: "readiness",
    primaryNavigationGroups: ["risk_compliance", "automated_trading", "optimization"],
    allowedNavigationHrefs: [
      "/assets",
      "/execution/risk-approval",
      "/regulation",
      "/execution/settlement",
      "/execution/audit",
      "/reports",
      "/execution/automation-policies",
      "/execution/orchestrator",
      "/execution",
      "/execution/proposals",
      "/execution/simulation",
      "/market-rules",
      "/intelligence",
      "/settings",
    ],
    priorityActions: [
      "Review automation gates and approval state.",
      "Check settlement, audit trail, and regulatory eligibility.",
      "Keep reports and assumptions ready for management or audit.",
    ],
    priorityKpis: ["blocked_gates", "approval_status", "settlement_variance"],
    allowedAutomationActions: ["view_status", "approve_gate", "block_gate"],
  },
  market_operations: {
    id: "market_operations",
    label: "Market operations",
    layer: "internal",
    header: "Connector operations",
    focus: "Exchange routes, telemetry, credentials, handshakes, market rules, and live access readiness.",
    defaultNavigationHref: "/execution/market-connectors",
    defaultNavigationLabel: "Market Access & Data",
    defaultControlRoomTab: "readiness",
    primaryNavigationGroups: ["automated_trading", "market_intelligence", "risk_compliance"],
    allowedNavigationHrefs: [
      "/assets",
      "/execution/market-connectors",
      "/settings",
      "/market-rules",
      "/market-prices",
      "/execution/automation-policies",
      "/execution/orchestrator",
      "/execution/market-allocation",
      "/execution/proposals",
      "/execution/simulation",
      "/execution/risk-approval",
      "/regulation",
    ],
    priorityActions: [
      "Clear exchange, EMS, data, and settlement connector blockers.",
      "Validate market rules before route certification.",
      "Keep live adapter handshakes ready for supervised automation.",
    ],
    priorityKpis: ["connector_readiness", "credential_status", "handshake_status"],
    allowedAutomationActions: ["view_status", "run_handshake"],
  },
  forecast_quant: {
    id: "forecast_quant",
    label: "Forecast / quant",
    layer: "internal",
    header: "Model quality OS",
    focus: "Forecast quality, actual-price evidence, signal reliability, optimizer behavior, and scenario stress.",
    defaultNavigationHref: "/forecasts",
    defaultNavigationLabel: "Forecast Trust",
    defaultControlRoomTab: "commercial",
    primaryNavigationGroups: ["market_intelligence", "optimization", "portfolio"],
    allowedNavigationHrefs: [
      "/forecasts",
      "/market-prices",
      "/market-signals",
      "/dispatch",
      "/scenarios",
      "/intelligence",
      "/revenue",
    ],
    priorityActions: [
      "Validate forecast and price evidence.",
      "Review dispatch optimizer assumptions.",
      "Use scenarios to stress test revenue and risk.",
    ],
    priorityKpis: ["forecast_error", "profit_per_mw_day", "revenue_stack"],
    allowedAutomationActions: ["view_status", "run_scenarios"],
  },
  revenue_analyst: {
    id: "revenue_analyst",
    label: "Revenue analyst",
    layer: "internal",
    header: "Commercial analytics OS",
    focus: "Tradable revenue streams, allocation economics, hedge alternatives, and blocked product value.",
    defaultNavigationHref: "/revenue",
    defaultNavigationLabel: "Revenue Assurance",
    defaultControlRoomTab: "commercial",
    primaryNavigationGroups: ["portfolio", "optimization", "market_intelligence", "automated_trading"],
    allowedNavigationHrefs: [
      "/revenue",
      "/hedging",
      "/scenarios",
      "/market-rules",
      "/execution/market-allocation",
      "/execution/settlement",
      "/dispatch",
      "/forecasts",
      "/market-signals",
      "/market-prices",
      "/reports",
    ],
    priorityActions: [
      "Refresh revenue stack and market allocation.",
      "Quantify blocked product value.",
      "Translate dispatch economics into owner and investor evidence.",
    ],
    priorityKpis: ["revenue_stack", "blocked_value", "hedged_revenue"],
    allowedAutomationActions: ["view_status", "run_scenarios"],
  },
};

export function isPersonaId(value: string): value is PersonaId {
  return PERSONA_IDS.includes(value as PersonaId);
}
